// <auto-generated />
using System;
using EdsmDbImporter;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace EdsmDbImporter.Migrations
{
    [DbContext(typeof(EdsmDbContext))]
    partial class EdsmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("EdsmDbImporter.CalculatorModels.CelestialBody", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double?>("AbsoluteMagnitude")
                        .HasColumnType("double precision");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<double?>("ArgOfPeriapsis")
                        .HasColumnType("double precision");

                    b.Property<string>("AtmosphereType")
                        .HasColumnType("text");

                    b.Property<double?>("AxialTilt")
                        .HasColumnType("double precision");

                    b.Property<int?>("DistanceToArrival")
                        .HasColumnType("integer");

                    b.Property<double?>("EarthMasses")
                        .HasColumnType("double precision");

                    b.Property<long?>("EdSystemId")
                        .HasColumnType("bigint");

                    b.Property<long?>("EdSystemId64")
                        .HasColumnType("bigint");

                    b.Property<string>("EdSystemName")
                        .HasColumnType("text");

                    b.Property<int?>("EdsmBodyId")
                        .HasColumnType("integer");

                    b.Property<long>("EdsmId")
                        .HasColumnType("bigint");

                    b.Property<long?>("EdsmId64")
                        .HasColumnType("bigint");

                    b.Property<double?>("Gravity")
                        .HasColumnType("double precision");

                    b.Property<bool?>("IsLandable")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsMainStar")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsScoopable")
                        .HasColumnType("boolean");

                    b.Property<string>("Luminosity")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<double?>("OrbitalEccentricity")
                        .HasColumnType("double precision");

                    b.Property<double?>("OrbitalInclination")
                        .HasColumnType("double precision");

                    b.Property<double?>("OrbitalPeriod")
                        .HasColumnType("double precision");

                    b.Property<double?>("Radius")
                        .HasColumnType("double precision");

                    b.Property<string>("ReserveLevel")
                        .HasColumnType("text");

                    b.Property<double?>("RotationalPeriod")
                        .HasColumnType("double precision");

                    b.Property<bool?>("RotationalPeriodTidallyLocked")
                        .HasColumnType("boolean");

                    b.Property<double?>("SemiMajorAxis")
                        .HasColumnType("double precision");

                    b.Property<double?>("SolarMasses")
                        .HasColumnType("double precision");

                    b.Property<double?>("SolarRadius")
                        .HasColumnType("double precision");

                    b.Property<string>("SpectralClass")
                        .HasColumnType("text");

                    b.Property<string>("SubType")
                        .HasColumnType("text");

                    b.Property<double?>("SurfacePressure")
                        .HasColumnType("double precision");

                    b.Property<int?>("SurfaceTemperature")
                        .HasColumnType("integer");

                    b.Property<string>("TerraformingState")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("VolcanismType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DistanceToArrival");

                    b.HasIndex("EdSystemId");

                    b.HasIndex("EdsmBodyId");

                    b.HasIndex("EdsmId");

                    b.HasIndex("Id");

                    b.HasIndex("SubType");

                    b.HasIndex("Type");

                    b.ToTable("CelestialBodies");
                });

            modelBuilder.Entity("EdsmDbImporter.CalculatorModels.CelestialBodyAtmosphereComposition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("BodyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BodyId");

                    b.ToTable("CelestialBodyAtmosphereCompositions");
                });

            modelBuilder.Entity("EdsmDbImporter.CalculatorModels.CelestialBodyBelt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("BodyId")
                        .HasColumnType("bigint");

                    b.Property<double>("InnerRadius")
                        .HasColumnType("double precision");

                    b.Property<double>("Mass")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<double>("OuterRadius")
                        .HasColumnType("double precision");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BodyId");

                    b.ToTable("CelestialBodyBelts");
                });

            modelBuilder.Entity("EdsmDbImporter.CalculatorModels.CelestialBodyMaterial", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("BodyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BodyId");

                    b.HasIndex("Key");

                    b.ToTable("CelestialBodyMaterials");
                });

            modelBuilder.Entity("EdsmDbImporter.CalculatorModels.CelestialBodyParent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("BodyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BodyId");

                    b.ToTable("CelestialBodyParents");
                });

            modelBuilder.Entity("EdsmDbImporter.CalculatorModels.CelestialBodyRing", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("BodyId")
                        .HasColumnType("bigint");

                    b.Property<double>("InnerRadius")
                        .HasColumnType("double precision");

                    b.Property<double>("Mass")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<double>("OuterRadius")
                        .HasColumnType("double precision");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BodyId");

                    b.ToTable("CelestialBodyRings");
                });

            modelBuilder.Entity("EdsmDbImporter.CalculatorModels.CelestialBodySolidComposition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("BodyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BodyId");

                    b.ToTable("CelestialBodySolidCompositios");
                });

            modelBuilder.Entity("EdsmDbImporter.CalculatorModels.EdSystem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long?>("CoordinatesId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("EdsmId")
                        .HasColumnType("bigint");

                    b.Property<long?>("EdsmId64")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CoordinatesId");

                    b.HasIndex("EdsmId");

                    b.HasIndex("EdsmId64");

                    b.HasIndex("Id");

                    b.HasIndex("Name");

                    b.ToTable("EdSystems");
                });

            modelBuilder.Entity("EdsmDbImporter.CalculatorModels.EdSystemCoordinates", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("X")
                        .HasColumnType("double precision");

                    b.Property<double>("Y")
                        .HasColumnType("double precision");

                    b.Property<double>("Z")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("EdSystemCoordinates");
                });

            modelBuilder.Entity("EdsmDbImporter.CalculatorModels.CelestialBody", b =>
                {
                    b.HasOne("EdsmDbImporter.CalculatorModels.EdSystem", null)
                        .WithMany("Bodies")
                        .HasForeignKey("EdSystemId");
                });

            modelBuilder.Entity("EdsmDbImporter.CalculatorModels.CelestialBodyAtmosphereComposition", b =>
                {
                    b.HasOne("EdsmDbImporter.CalculatorModels.CelestialBody", "Body")
                        .WithMany("BodyAtmosphereCompositions")
                        .HasForeignKey("BodyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EdsmDbImporter.CalculatorModels.CelestialBodyBelt", b =>
                {
                    b.HasOne("EdsmDbImporter.CalculatorModels.CelestialBody", "Body")
                        .WithMany("Belts")
                        .HasForeignKey("BodyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EdsmDbImporter.CalculatorModels.CelestialBodyMaterial", b =>
                {
                    b.HasOne("EdsmDbImporter.CalculatorModels.CelestialBody", "Body")
                        .WithMany("BodyMaterials")
                        .HasForeignKey("BodyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EdsmDbImporter.CalculatorModels.CelestialBodyParent", b =>
                {
                    b.HasOne("EdsmDbImporter.CalculatorModels.CelestialBody", "Body")
                        .WithMany("BodyParents")
                        .HasForeignKey("BodyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EdsmDbImporter.CalculatorModels.CelestialBodyRing", b =>
                {
                    b.HasOne("EdsmDbImporter.CalculatorModels.CelestialBody", "Body")
                        .WithMany("Rings")
                        .HasForeignKey("BodyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EdsmDbImporter.CalculatorModels.CelestialBodySolidComposition", b =>
                {
                    b.HasOne("EdsmDbImporter.CalculatorModels.CelestialBody", "Body")
                        .WithMany("BodySolidCompositions")
                        .HasForeignKey("BodyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EdsmDbImporter.CalculatorModels.EdSystem", b =>
                {
                    b.HasOne("EdsmDbImporter.CalculatorModels.EdSystemCoordinates", "Coordinates")
                        .WithMany()
                        .HasForeignKey("CoordinatesId");
                });
#pragma warning restore 612, 618
        }
    }
}
